on:
  push:

jobs:
  checks-source-code:
    timeout-minutes: 15
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3.2.0
      - name: Setup git access
        run: git config --global --add safe.directory $(realpath .)

      - name: Setup Hurl
        uses: nikeee/setup-hurl@v2

      - name: Prepare env file
        run: echo '${{ secrets.API_HOST }}' > .env.production

      - name: Up and run dev environment
        run: make up

      - name: Run integration tests
        run: make hurl

  build-and-push-images:
    timeout-minutes: 30
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: checks-source-code
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3.2.0

      - name: Prepare GCP auth
        run: mkdir secrets && echo '${{ secrets.GCP_STORAGE }}' > secrets/gcp-storage.json
      - name: Login to Google Artifact Registry
        uses: docker/login-action@v2
        with:
          registry: europe-west4-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GSA_REGISTRY_READWRITE_AUTH }}

      - name: Setup Hurl
        uses: nikeee/setup-hurl@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Up and run dev environment
        run: make dev-up

      - name: Build images
        run: make build-and-push-images

      - name: Run test container
        run: make dev-test-test-image

      - name: Run integration tests
        run: make dev-test-prod-image

      - name: Dump docker logs
        if: always()
        uses: jwalton/gh-docker-logs@v2

  markdown:
    timeout-minutes: 5
    runs-on: ubuntu-22.04
    steps:
      - name: Run mdl for check markdown format
        uses: nosborn/github-action-markdown-cli@v3.2.0
        with:
          files: .
          config_file: .markdownlint.yaml
