on:
  push:

jobs:
  checks-source-code:
    timeout-minutes: 15
    runs-on: ubuntu-22.04
    environment: dev
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3.2.0
      - name: Setup git access
        run: git config --global --add safe.directory $(realpath .)

      - name: Setup Hurl
        uses: nikeee/setup-hurl@v2

      - name: Prepare env file
        run: echo '${{ secrets.API_HOST }}' > .env.production

      - name: Up and run dev environment
        run: make up

      - name: Run integration tests
        run: make hurl
